import { 
  LayoutDashboard, 
  FileText, 
  ShieldCheck, 
  Landmark, 
  Activity, 
  Users, 
  Settings, 
  Bell,
  Search,
  Menu,
  LogOut,
  ChevronRight,
  UploadCloud,
  CheckCircle,
  AlertCircle,
  FileBadge,
  Link as LinkIcon,
  Truck,
  FileSignature,
  Database,
  History,
  UserCog,
  Server,
  X
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Document: FileText,
  Security: ShieldCheck,
  Bank: Landmark,
  Chart: Activity,
  Users: Users,
  Settings: Settings,
  Notification: Bell,
  Search: Search,
  Menu: Menu,
  Logout: LogOut,
  ArrowRight: ChevronRight,
  Upload: UploadCloud,
  Check: CheckCircle,
  Alert: AlertCircle,
  Contract: FileBadge,
  Chain: LinkIcon,
  Truck: Truck,
  Signature: FileSignature,
  Database: Database,
  History: History,
  Admin: UserCog,
  Server: Server,
  Close: X
};